repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^python/sitstart/aws/cloudformation/templates
        args: ["--unsafe"]
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        name: Prettier Formatter (json)
        types_or: [json]
  - repo: https://github.com/awslabs/cfn-python-lint
    rev: v0.86.1
    hooks:
      - id: cfn-python-lint
        files: python/sitstart/aws/cloudformation/templates/.*\.(json|yml|yaml)$
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix]
      - id: ruff-format
        types_or: [python, pyi, jupyter]
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.8.0-1
    hooks:
      - id: shfmt
        types: [shell]
        args: [--indent, "2", "--write"]
  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.18
    hooks:
      - id: shellcheck
        types: [shell]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.359
    hooks:
      - id: pyright
  - repo: local
    hooks:
      - id: push-system-files
        name: System file archive
        files: ^system/files/.*
        pass_filenames: false
        language: python
        entry: python/sitstart/scripts/push_system_files.py
        additional_dependencies: [boto3, checksumdir]
