[tool.ruff]
src = ["python"]

[tool.ruff.lint.isort]
known-first-party = ["ktd", "sit", "sitstart"]

[tool.pyright]
venvPath = "."
venv = ".venv"
typeCheckingMode = "basic"
extraPaths = ["python"]

[tool.coverage.run]
include = ["python/*"]
