[tool.ruff]
src = ["python"]

[tool.ruff.lint.isort]
known-first-party = ["ktd", "sit", "sitstart"]

[tool.pyright]
venvPath = "."
venv = ".venv"
typeCheckingMode = "basic"
extraPaths = ["python"]

[tool.pytest.ini_options]
filterwarnings = [
  "ignore::DeprecationWarning",
  "ignore::PendingDeprecationWarning",
  'ignore: You are trying to `self.log\(\)`',
]

[tool.coverage.run]
include = ["python/*"]
