[tool.ruff]
src = ["python"]

[tool.ruff.lint.isort]
known-first-party = ["sit", "sitstart"]

[tool.pyright]
venvPath = "."
venv = ".venv"
typeCheckingMode = "basic"
extraPaths = ["python"]

[tool.coverage.run]
include = ["python/*"]

[tool.pytest.ini_options]
filterwarnings = [
  "ignore::DeprecationWarning",
  "ignore::PendingDeprecationWarning",
  'ignore: You are trying to `self.log\(\)`',
  "ignore: GPU available but not used",
  "ignore: .*Consider increasing the value of the `num_workers` argument",
]
markers = [
  "slow: mark test as slow to run",
  "integration: mark test as integration test",
]
addopts = ["--import-mode=importlib", "--tb=short"]
