cluster_name: g5g
max_workers: 4
upscaling_speed: 1.0
idle_timeout_minutes: 10
provider:
  type: aws
  region: us-west-2
  availability_zone: us-west-2a,us-west-2b,us-west-2c
auth:
  ssh_user: ec2-user
  ssh_private_key: ~/.ssh/rsa.pem
available_node_types:
  ray.head.default:
    max_workers: 0
    resources: {}
    node_config:
      InstanceType: m6a.xlarge
      ImageId: ami-0c38021ff804d9342
      KeyName: rsa
      IamInstanceProfile:
        Arn: arn:aws:iam::960487471244:instance-profile/ray-head
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 256
            VolumeType: gp3
  ray.worker.default:
    min_workers: 0
    max_workers: 4
    resources: {"CPU": 8, "GPU": 1}
    node_config:
      InstanceType: g5.2xlarge
      ImageId: ami-0c38021ff804d9342
      KeyName: rsa
      IamInstanceProfile:
        Arn: arn:aws:iam::960487471244:instance-profile/ray-worker
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 256
            VolumeType: gp3
head_node_type: ray.head.default
file_mounts: {
    # contents of the dev repo
    "~/dev": "~/dev",
    # contents of the dotfiles repo
    "~/.aws/config": "~/.aws/config",
    "~/.local/bin/scm-prompt.sh": "~/.local/bin/scm-prompt.sh",
    "~/.bash_profile": "~/.bash_profile",
    "~/.bashrc": "~/.bashrc",
    "~/.ipython/profile_default/ipython_config.py": "~/.ipython/profile_default/ipython_config.py",
    "~/.ipython/profile_default/ipython_kernel_config.py": "~/.ipython/profile_default/ipython_kernel_config.py",
  }
cluster_synced_files: []
file_mounts_sync_continuously: False
rsync_exclude:
  - "**/.git"
  - "**/.git/**"
rsync_filter:
  - ".gitignore"
initialization_commands: []
setup_commands:
  # login and configure wandb
  - mkdir -p $WANDB_DIR
  - wandb login
head_setup_commands:
  # create the prometheus service file
  - |
    sudo cp "$DEV/core/python/ktd/ray/config/aux/prometheus.service" \
      /etc/systemd/system/prometheus.service
  # update the fluent-bit config
  - |
    sudo mkdir -p /etc/fluent-bit &&
      sudo cp "$DEV/core/python/ktd/ray/config/aux/fluent-bit-head.conf" \
        /etc/fluent-bit/fluent-bit.conf
  # update the grafana service file to ensure grafana can acccess Ray
  # config files in /tmp/ray
  - |
    sudo sed -i 's/^PrivateTmp=true/PrivateTmp=false/g' \
      /usr/lib/systemd/system/grafana-server.service
  # update the grafana service config
  - |
    sudo test -f /etc/grafana/grafana.ini.ray-bak || (
      sudo cp /etc/grafana/grafana.ini /etc/grafana/grafana.ini.ray-bak &&
        sudo cp "$DEV/core/python/ktd/ray/config/aux/grafana.ini" \
          /etc/grafana/grafana.ini)
  # install loki TODO: move to AMI
  - |
    yum list installed loki >/dev/null 2>&1 || 
      sudo -- bash -c 'source ~ec2-user/dev/core/scripts/ec2_dev_setup.sh; \
        install_components loki'
worker_setup_commands: []
head_start_ray_commands:
  # restart ray
  - ray stop
  - |
    ray start --head --port=6379 --object-manager-port=8076 \
      --autoscaling-config=~/ray_bootstrap_config.yaml \
      --dashboard-host=0.0.0.0 --ray-debugger-external
  # add loki dashboard and datasource to grafana
  - |
    cp "$DEV/core/python/ktd/ray/config/aux/loki_grafana_datasource.yml" \
      /tmp/ray/session_latest/metrics/grafana/provisioning/datasources
    cp "$DEV/core/python/ktd/ray/config/aux/loki_grafana_dashboard.json" \
      /tmp/ray/session_latest/metrics/grafana/dashboards/

  # restart services
  - sudo systemctl restart grafana-server
  - sudo systemctl restart prometheus
  - sudo systemctl restart fluent-bit
  - sudo systemctl restart loki
worker_start_ray_commands:
  # restart ray
  - ray stop
  - |
    ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076 \
      --ray-debugger-external
  # update the fluent-bit config with $RAY_HEAD_IP
  - |
    sudo mkdir -p /etc/fluent-bit &&
      cat "$DEV/core/python/ktd/ray/config/aux/fluent-bit-worker.conf" |
        envsubst | sudo tee /etc/fluent-bit/fluent-bit.conf
  # restart the fluent-bit service
  - sudo systemctl restart fluent-bit
